Vizblocks: Draw a bar chart
VisualizationLiteracyPlayground/scratch-vm pull request #8
Opened 2020-03-27 16:38 UTC by FotoWu

Created one block to draw the bar chart:
- draw bar

2020-03-28 16:02 UTC, tanhengyeow requested changes
Good work on these charts! Just some minor stuff to address. 

Also, do a quick check on the existing charts to make sure their implementation is not affected.

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +        this._xCenter = -160;
Declared on line 80 already
```suggestion
```

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +        this._yCenter = -100;
Declared on line 81 already
```suggestion
```

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +                            defaultValue: 'histogram'
The default value can be still 'dot plot', histograms are less commonly used for younger children.

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +                            defaultValue: 'histogram'
Same here.

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +                            defaultValue: 'histogram'
Same here.

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +                        default: 'draw bar',
```suggestion
                        default: 'draw bars',
```

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +                    opcode: 'drawBar',
Change all to `drawBars`

```suggestion
                    opcode: 'drawBars',
```

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +                console.log(divider);
Can remove this line.

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +                    // extract the first 5 chars to avoid long labels on X axis
```suggestion
                    // extract the first 3 chars to avoid long labels on the x-axis
```

2020-03-28 16:02 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> +            if (type === '' || type === 'axes') {
When will type be `''` ?

2020-03-28 18:19 UTC, FotoWu commented on src/extensions/scratch3_vizblocks/index.js
> +            if (type === '' || type === 'axes') {
type === '' is for old version because it's a new parameter, in case that it's not passed somewhere, but now I think I can remove this

2020-03-28 19:41 UTC, FotoWu commented
Bar chart
![bar-chart](https://user-images.githubusercontent.com/30313526/77832186-12445c80-716f-11ea-81e1-4b1580fd8800.jpg)
Histogram
![histogram](https://user-images.githubusercontent.com/30313526/77832193-1c665b00-716f-11ea-8492-8545dbc8b8e5.jpg)

2020-03-29 02:23 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
> -        this._yCenter = -100;
We should still keep these 2 lines here, now there are no declarations for `this._xCenter` and `this._yCenter` anymore.

2020-03-29 03:05 UTC, tanhengyeow commented on src/extensions/scratch3_vizblocks/index.js
>                          },
The y-axis option doesn't have dot plot, in this case we can default to line chart

2020-03-29 08:09 UTC, tanhengyeow requested changes
Thanks for the quick fix! Just a few more things and this should be good to go!

- [x] Drawing bar charts/histograms multiple times shows overlapping contents, the `clear` function should be updated to solve this issue.

- [x] Labels for x-axis categories in bar charts should start from the interval point as they appear too far for charts with lesser bars.

![image](https://user-images.githubusercontent.com/25320782/77844255-d0033580-71d7-11ea-9926-fef3e62c10af.png)

- [x]  The x-axis line should be extended as the histogram bars look disjoint if it appears at the end.

![image](https://user-images.githubusercontent.com/25320782/77844251-c5e13700-71d7-11ea-8cf5-0dfaa13d51b8.png)

- [x] Text + string labels should be visible and working.

![image](https://user-images.githubusercontent.com/25320782/77844264-df827e80-71d7-11ea-8376-94321c1983d4.png)

2020-03-29 08:47 UTC, tanhengyeow approved these changes

2020-03-29 08:47 UTC, merged